---
title: "Data Wrangling II"
output: html_document
---

Classwork:

# Data wrangling  2

```{r}
library(tidyverse)
library(rvest)
library(httr)

url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html

```


```{r}

drug_use_html %>%
  html_nodes(css = "table") %>%
  first() %>%
  html_table() %>%
  slice(-1) %>%
  as_tibble()
```
# Data Wrangling III

```{R}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat")   %>% janitor::clean_names()
head(pulse_data)

#wide format to long format

pulse_long = pulse_data %>% pivot_longer(bdi_score_bl:bdi_score_12m , 
names_to = "visit",
names_prefix = "bdi_score_",
values_to = "bdi_score") %>% relocate(id, visit) %>% mutate(visit=recode(visit, "bl" = "00m"))

head(pulse_long)
```
Stacking data and binding rows

```{R}
fellowship_data = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6") %>% mutate(movie= "fellowship_ring")

two_towers_data = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "F3:H6") %>% mutate(movie= "two_towers")

return_king_data = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "J3:L6") %>% mutate(movie= "return_king")

lotr_tidy= bind_rows(fellowship_data, two_towers_data, return_king_data) %>%
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(female:male, names_to = "gender", values_to = "words")

```
joining datasets

```{R}
pup_data = 
  read_csv("./data_import_examples/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  relocate(litter_number) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))
#join litter data on to pups

left_join (pup_data, litter_data, by = "litter_number")
```

